apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: production
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: production
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        svc.tudoonline.io/role: db
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          # value: "STHVJWHrvGc91MiY1ya9DDFMA6v0uGvX"
          value: "ncpfxmbOTXqTflm0ieHI1174OJMZkl9A" #root rds
        - name: MYSQL_DATABASE
          value: "tudoonline"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "16Gi"
            cpu: "4000m"
          limits:
            memory: "20Gi"
            cpu: "8000m"
        args:
        - "--innodb-buffer-pool-size=14G"
        - "--max-connections=1000"
        - "--innodb-redo-log-capacity=2147483648"
        - "--innodb-flush-log-at-trx-commit=2"
        - "--replica-skip-errors=1062,1032"
        - "--binlog-expire-logs-seconds=604800"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 280Gi
          