#!/usr/bin/env groovy
pipeline {
  environment { 
    AWS_REGION = "us-east-1"
    AWS_ACCOUNT_ID = '967910066457'
    HELM_CHART_NAME = 'tudoonline'
    HELM_TIMEOUT = '600s'
    HELM_REPO_CUSTOM_NAME = 'tudoonline-stable'
    HELM_REPO_CUSTOM_URL = 's3://tudoonline-helm-charts/stable'
    KUBERNETES_SERVER_URL = "https://kubernetes.default"
    JENKINS_ENVIRONMENT_CREDENTIAL_ID = 'jenkins@git'
    JENKINS_APP_CREDENTIAL_ID = 'tudoonline-workers@git'
    SQUADCAST_URL = "jenkins@squadcast"
    NOTIFICATIONS_EMAILS = 'marcosilveira39@gmail.com'
    GIT_CRYPT_KEY = 'tudoonline-legadogool-workers-secretkey-git-crypt'
  } 

  options { 
    timeout(time: 30, unit: 'MINUTES') 
    skipDefaultCheckout()
  } 

  agent {
    kubernetes { 
      inheritFrom 'jenkins-slave-docker-build'
      defaultContainer 'k8s-jenkins-toolbox'
    }
  }

  stages {
    stage('Checkout') {
      steps {
        script {
          GIT_ENVIRONMENT_URL = 'git@gitlab-ssh.ganex.com.br:clients/tudo-online/projects/tudoonline-workers.git'
          GIT_APP_URL = 'git@github.com:tudoonline/legadogool-workers.git'
          if (GIT_BRANCH == 'master') {
            NAMESPACE = "production"
            HELM_VALUES_FILE = "helm-values-${NAMESPACE}.yaml"
            HELM_RELEASE_NAME = 'tudoonline-workers'
            HELM_CHART_VERSION = "1.0.x"
            ECR_REPO_NAME = 'tudoonline-workers-production'
            GIT_ENVIRONMENT_BRANCH = 'master'
            GIT_APP_BRANCH = 'master'
            AWS_ROLE_ARN = "arn:aws:iam::${AWS_ACCOUNT_ID}:role/tudoonline-workers-production"
            KUBERNETES_CREDENTIAL_ID = "jenkins-production"
            TRIVY_SEVERITY = "CRITICAL"
            TRIVY_EXIT_CODE = "0"
          } else {
            sh """
              echo "Branch ${GIT_BRANCH} not found, terminating..."
              exit 1
            """
          }
          checkout([$class: 'GitSCM', branches: [[name: "refs/heads/${GIT_ENVIRONMENT_BRANCH}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CloneOption', depth: 2, noTags: false, reference: '', shallow: true]], submoduleCfg: [], userRemoteConfigs: [[refspec: "+refs/heads/${GIT_ENVIRONMENT_BRANCH}", credentialsId: "${JENKINS_ENVIRONMENT_CREDENTIAL_ID}", url: "${GIT_ENVIRONMENT_URL}"]]])
          dir('app') {
            checkout([$class: 'GitSCM', branches: [[name: "refs/heads/${GIT_APP_BRANCH}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CloneOption', depth: 2, noTags: false, reference: '', shallow: true]], submoduleCfg: [], userRemoteConfigs: [[refspec: "+refs/heads/${GIT_APP_BRANCH}", credentialsId: "${JENKINS_APP_CREDENTIAL_ID}", url: "${GIT_APP_URL}"]]])
          }
        }
      }
    }

    stage('Initialize') {
      steps {
        withEnv(["AWS_ROLE_ARN=${AWS_ROLE_ARN}", "AWS_REGION=${AWS_REGION}"]) {
          withCredentials([file(credentialsId: "${GIT_CRYPT_KEY}", variable: 'DECRYPT_KEY')]) {
            sh """
              \$(aws ecr get-login --no-include-email --region ${AWS_REGION})
              helm repo add ${HELM_REPO_CUSTOM_NAME} ${HELM_REPO_CUSTOM_URL}
            """
            container('trivy') {
              sh """
                mkdir -p ${WORKSPACE}/trivy-reports/
                trivy image --download-db-only
              """
            }
            dir('app') {
              sh """
                git-crypt unlock $DECRYPT_KEY
              """
            }
          }
        }
      }
    }

    stage('Build Docker Images') {
      parallel {
        stage('worker') {
          steps {
            withEnv(['DOCKER_IMAGE=worker']) {
              sh """
                docker build --network host -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}/${DOCKER_IMAGE}:${BUILD_NUMBER} -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}/${DOCKER_IMAGE}:latest --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}/${DOCKER_IMAGE}:latest --build-arg BUILDKIT_INLINE_CACHE=1 -f docker/${DOCKER_IMAGE}/Dockerfile .
                docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}/${DOCKER_IMAGE}:${BUILD_NUMBER} && docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}/${DOCKER_IMAGE}:latest
              """
            }
          }
        }
      }
    }

    stage('Security Scan') {
      when { environment name: 'SKIP_SECURITY_SCAN', value: 'false' }
      parallel {
        stage('worker') {
          steps {
            container('trivy') {
              withEnv(['DOCKER_IMAGE=worker', "TRIVY_IGNOREFILE=${WORKSPACE}/.trivyignore", "TRIVY_SECRET_CONFIG=${WORKSPACE}/.trivy-secret.yaml"]) {
                sh """
                  cd /
                  trivy image --vuln-type os --no-progress --format template --template @contrib/html.tpl -o ${WORKSPACE}/trivy-reports/${DOCKER_IMAGE}-OS.html ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}/${DOCKER_IMAGE}:${BUILD_NUMBER}
                  trivy image --vuln-type library --no-progress --format template --template @contrib/html.tpl -o ${WORKSPACE}/trivy-reports/${DOCKER_IMAGE}-Library.html ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}/${DOCKER_IMAGE}:${BUILD_NUMBER}
                  trivy config --format table -o ${WORKSPACE}/trivy-reports/${DOCKER_IMAGE}-Dockerfile.txt ${WORKSPACE}/docker/${DOCKER_IMAGE}
                  trivy image --exit-code ${TRIVY_EXIT_CODE} --severity ${TRIVY_SEVERITY} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}/${DOCKER_IMAGE}:${BUILD_NUMBER}
                  trivy config --exit-code ${TRIVY_EXIT_CODE} --severity ${TRIVY_SEVERITY} ${WORKSPACE}/docker/${DOCKER_IMAGE}
                """
              }
            }
          }
        }
      }
    }

    stage('Deploy') {
      steps {
        withEnv(["AWS_ROLE_ARN=${AWS_ROLE_ARN}", "AWS_REGION=${AWS_REGION}"]) {
          withKubeConfig([credentialsId: "${KUBERNETES_CREDENTIAL_ID}", serverUrl: "${KUBERNETES_SERVER_URL}"]) {
            sh "helm upgrade --install ${HELM_RELEASE_NAME} --namespace ${NAMESPACE} -f ${HELM_VALUES_FILE} --set job.defaults.imageTag=${BUILD_NUMBER} --set worker.defaults.imageTag=${BUILD_NUMBER} --set cron.defaults.imageTag=${BUILD_NUMBER} --set cronjob.defaults.imageTag=${BUILD_NUMBER} ${HELM_REPO_CUSTOM_NAME}/${HELM_CHART_NAME} --wait --timeout ${HELM_TIMEOUT} --version ${HELM_CHART_VERSION} --atomic"
          }
        }
      }
    }
  }
  
  post {
    always {
      publishHTML([allowMissing: true, alwaysLinkToLastBuild: true, keepAll: true, reportDir: "${WORKSPACE}/trivy-reports/", reportFiles: "", reportName: "Trivy Security Scan", reportTitles: ""])
      
    }
    failure {
      script {
        squadcastNotifier()
        emailext to: "${NOTIFICATIONS_EMAILS}", subject: "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} - ${currentBuild.currentResult}", body: "Job ${env.JOB_NAME} was finished with ${currentBuild.currentResult}, check console output at ${env.BUILD_URL} to view the results"
      }
    }
  }
}

